import React from 'react';
import { 
  Sparkles, 
  ArrowRight, 
  Compass, 
  Dna, 
  BrainCircuit, 
  Layers, 
  Volume2, 
  Trophy, 
  CheckCircle2, 
  Play, 
  Bot,
  Zap,
  Shield,
  Activity
} from 'lucide-react';

interface LandingPageProps {
  onStartLearning: () => void;
  onStartDemoTour: () => void;
}

export const LandingPage: React.FC<LandingPageProps> = ({
  onStartLearning,
  onStartDemoTour,
}) => {
  return (
    <div className="space-y-16 pb-16">
      {/* Hero Section */}
      <section className="relative overflow-hidden pt-6 sm:pt-10">
        <div className="max-w-5xl mx-auto text-center space-y-6">
          {/* Top Badge */}
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-bold bg-blue-50 text-blue-700 border border-blue-200/80 shadow-xs">
            <span className="w-2 h-2 rounded-full bg-blue-600 animate-pulse" />
            <span>AI Model Development Contest 2026 • Biology Education</span>
          </div>

          {/* Main Title & Tagline */}
          <div className="space-y-3">
            <h1 className="text-4xl sm:text-6xl font-black text-slate-900 tracking-tight leading-[1.1]">
              BioSphere <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600">AI</span>
            </h1>
            <p className="text-xl sm:text-2xl font-bold text-slate-600">
              Explore. Understand. Learn with AI.
            </p>
          </div>

          <p className="text-sm sm:text-base text-slate-600 max-w-2xl mx-auto leading-relaxed">
            Step inside a dynamic, photorealistic 3D human cell. Rotate organelles, listen to 
            multi-level biological explanations generated by <strong>Gemini AI</strong>, conduct hands-on interactive activities, 
            and observe mitosis cell division step-by-step.
          </p>

          {/* Action CTA Buttons */}
          <div className="pt-2 flex flex-wrap items-center justify-center gap-4">
            <button
              onClick={onStartLearning}
              className="py-4 px-8 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white font-extrabold text-sm sm:text-base shadow-xl shadow-blue-500/25 flex items-center gap-2.5 transition-all hover:scale-[1.02]"
            >
              <span>Start Learning in 3D</span>
              <ArrowRight className="w-5 h-5" />
            </button>

            <button
              onClick={onStartDemoTour}
              className="py-4 px-6 rounded-2xl bg-white hover:bg-slate-50 text-slate-800 font-bold text-sm sm:text-base border border-slate-200 shadow-sm flex items-center gap-2 transition-all hover:border-slate-300"
            >
              <Play className="w-4 h-4 text-blue-600 fill-blue-600" />
              <span>Launch 2-Min Demo Flow</span>
            </button>
          </div>

          {/* Quick Pillars bar */}
          <div className="pt-8 grid grid-cols-2 sm:grid-cols-4 gap-3 text-left">
            <div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-xs flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center shrink-0">
                <Compass className="w-5 h-5" />
              </div>
              <div>
                <div className="text-xs font-bold text-slate-900">Interactive 3D</div>
                <div className="text-[11px] text-slate-500">Real-time Three.js</div>
              </div>
            </div>

            <div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-xs flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-purple-50 text-purple-600 flex items-center justify-center shrink-0">
                <Sparkles className="w-5 h-5" />
              </div>
              <div>
                <div className="text-xs font-bold text-slate-900">Gemini 3.8 AI</div>
                <div className="text-[11px] text-slate-500">Multi-level Explanations</div>
              </div>
            </div>

            <div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-xs flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center shrink-0">
                <Volume2 className="w-5 h-5" />
              </div>
              <div>
                <div className="text-xs font-bold text-slate-900">Voice Learning</div>
                <div className="text-[11px] text-slate-500">Speech Synthesis</div>
              </div>
            </div>

            <div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-xs flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center shrink-0">
                <Trophy className="w-4 h-4" />
              </div>
              <div>
                <div className="text-xs font-bold text-slate-900">Adaptive Quizzes</div>
                <div className="text-[11px] text-slate-500">Diagnostic Scoring</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 3 Core Curriculum Modules Preview */}
      <section className="max-w-5xl mx-auto space-y-6">
        <div className="text-center space-y-2">
          <span className="text-xs font-bold uppercase tracking-wider text-blue-600 bg-blue-50 px-3 py-1 rounded-full border border-blue-200">
            Syllabus Aligned
          </span>
          <h2 className="text-2xl sm:text-3xl font-black text-slate-900 tracking-tight">
            Comprehensive Cell Biology Curriculum
          </h2>
          <p className="text-xs sm:text-sm text-slate-500 max-w-xl mx-auto">
            Covering all foundational high school and undergraduate cellular mechanisms.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Card 1 */}
          <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm space-y-4 hover:border-blue-300 transition-all">
            <div className="w-12 h-12 rounded-2xl bg-sky-50 text-sky-600 flex items-center justify-center font-black text-xl">
              🛡️
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900">Unit 1: Cell Structure</h3>
              <p className="text-xs text-slate-500 leading-relaxed mt-1">
                Explore the fluid mosaic phospholipid bilayer, cholesterol buffers, and the gel-like cytoplasm matrix.
              </p>
            </div>
            <ul className="text-xs text-slate-600 space-y-1.5 pt-2 border-t border-slate-100">
              <li className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />
                <span>Membrane Permeability & Channels</span>
              </li>
              <li className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />
                <span>Cytosolic Colloidal Diffusion</span>
              </li>
            </ul>
          </div>

          {/* Card 2 */}
          <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm space-y-4 hover:border-blue-300 transition-all">
            <div className="w-12 h-12 rounded-2xl bg-orange-50 text-orange-600 flex items-center justify-center font-black text-xl">
              ⚡
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900">Unit 2: Cell Organelles</h3>
              <p className="text-xs text-slate-500 leading-relaxed mt-1">
                Deep dive into the 8 major organelle powerhouses, protein folding highways, and postal Golgi cisternae.
              </p>
            </div>
            <ul className="text-xs text-slate-600 space-y-1.5 pt-2 border-t border-slate-100">
              <li className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />
                <span>Mitochondria ATP Synthase</span>
              </li>
              <li className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />
                <span>Rough ER & Golgi Transport</span>
              </li>
            </ul>
          </div>

          {/* Card 3 */}
          <div className="bg-white p-6 rounded-3xl border border-slate-200 shadow-sm space-y-4 hover:border-blue-300 transition-all">
            <div className="w-12 h-12 rounded-2xl bg-purple-50 text-purple-600 flex items-center justify-center font-black text-xl">
              🧬
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900">Unit 3: Cell Division</h3>
              <p className="text-xs text-slate-500 leading-relaxed mt-1">
                Interact with the full mitotic sequence from Interphase chromatin doubling through Cytokinesis pinching.
              </p>
            </div>
            <ul className="text-xs text-slate-600 space-y-1.5 pt-2 border-t border-slate-100">
              <li className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />
                <span>PMAT Mitotic Stages Simulation</span>
              </li>
              <li className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" />
                <span>Contractile Ring Scission</span>
              </li>
            </ul>
          </div>
        </div>
      </section>

      {/* AI Features Showcase Section */}
      <section className="max-w-5xl mx-auto bg-gradient-to-br from-slate-900 via-indigo-950 to-slate-900 text-white rounded-3xl p-8 sm:p-10 shadow-xl border border-indigo-900/60 space-y-8">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-white/10 pb-6">
          <div>
            <span className="text-xs font-bold uppercase tracking-wider text-cyan-400">
              Visible Intelligent Workflow
            </span>
            <h2 className="text-2xl sm:text-3xl font-black text-white mt-1">
              Where Gemini AI Empowers the Learner
            </h2>
          </div>
          <span className="text-xs font-semibold bg-blue-500/20 text-cyan-300 border border-blue-400/30 px-3 py-1 rounded-full shrink-0">
            Powered by Gemini AI (gemini-3.8-flash)
          </span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="bg-white/5 p-4 rounded-2xl border border-white/10 space-y-2">
            <Sparkles className="w-5 h-5 text-cyan-400" />
            <h4 className="font-bold text-sm text-white">Tiered Explanations</h4>
            <p className="text-xs text-slate-300 leading-relaxed">
              Dynamically generates beginner, intermediate, and advanced pedagogical analogies and exam memory tricks.
            </p>
          </div>

          <div className="bg-white/5 p-4 rounded-2xl border border-white/10 space-y-2">
            <BrainCircuit className="w-5 h-5 text-purple-400" />
            <h4 className="font-bold text-sm text-white">Contextual AI Tutor</h4>
            <p className="text-xs text-slate-300 leading-relaxed">
              Answers student inquiries with full awareness of the active organelle and past quiz misunderstandings.
            </p>
          </div>

          <div className="bg-white/5 p-4 rounded-2xl border border-white/10 space-y-2">
            <Trophy className="w-5 h-5 text-yellow-400" />
            <h4 className="font-bold text-sm text-white">Adaptive AI Quizzes</h4>
            <p className="text-xs text-slate-300 leading-relaxed">
              Creates fresh, medically and biologically verified 4-choice questions with scientific rationale for each option.
            </p>
          </div>

          <div className="bg-white/5 p-4 rounded-2xl border border-white/10 space-y-2">
            <Activity className="w-5 h-5 text-emerald-400" />
            <h4 className="font-bold text-sm text-white">Personalized Diagnosis</h4>
            <p className="text-xs text-slate-300 leading-relaxed">
              Audits quiz errors to pinpoint weak biochemical topics and delivers targeted revision roadmaps.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};
